# Generated by Django 5.1.1 on 2025-03-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_appuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='User Address'),
        ),
    ]
