# Generated by Django 5.1.1 on 2025-04-08 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_appuser_options_appuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 17, 25, 7, 147718)),
        ),
    ]
