# Generated by Django 5.1.1 on 2025-04-09 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_appuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 13, 46, 26, 869276)),
        ),
    ]
