# Generated by Django 5.1.1 on 2025-04-09 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_appuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 23, 56, 29, 386561)),
        ),
    ]
