# Generated by Django 5.1.1 on 2025-04-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_alter_appuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticationlevel',
            name='biometric_verified',
        ),
        migrations.AlterField(
            model_name='authenticationlevel',
            name='current_level',
            field=models.IntegerField(choices=[(1, 'Basic - Password only'), (2, 'Two-factor')], default=1),
        ),
    ]
